name: Anchor Test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SOLANA_CLI_VERSION: 1.17.31
  ANCHOR_VERSION: 0.29.0

jobs:
  anchor-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Solana CLI
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.17.31/install)"
      - name: Reload PATH
        run: |
          source ~/.profile && source ~/.bash_profile
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          solana --version
      - name: Install dependencies
        run: |
          npm i -g @project-serum/anchor-cli@0.29.0
          npm install
          