name: Anchor Test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  SOLANA_CLI_VERSION: 1.17.31
  ANCHOR_VERSION: 0.29.0

jobs:
  anchor-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
